// packages/react/src/Calendar.tsx
/**
 * Root calendar component. Accepts either calendar `options` or an existing
 * `store`, wires the host callbacks into context, renders the toolbar and the
 * active view, and provides minimal keyboard navigation.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import type {
  CalendarOptions,
  CalendarStore,
  ViewModel,
} from "@calidar/core";
import {
  computeView,
  addDays,
  epochToPlainDate,
  startOfDayEpoch,
} from "@calidar/core";
import { useCalendar } from "./useCalendar.js";
import {
  CalendarContext,
  type CalendarCallbacks,
  type CompactNav,
} from "./context.js";
import { CalendarToolbar } from "./CalendarToolbar.js";
import { TimeGridView } from "./TimeGridView.js";
import { MonthView } from "./MonthView.js";
import { AgendaView } from "./AgendaView.js";
import { createFormatters } from "./format.js";

export interface CalendarProps extends CalendarCallbacks {
  /** Calendar configuration (used to create a store if `store` is absent). */
  options?: CalendarOptions;
  /** An existing store to drive this calendar (overrides `options`). */
  store?: CalendarStore;
  /** Hide the built-in toolbar (host renders its own controls). */
  hideToolbar?: boolean;
  /**
   * BCP-47 locale for all labels (weekdays, titles, times). Overrides
   * `navigator.language`. Omit to keep the host's runtime locale (default).
   */
  locale?: string;
  /**
   * Force a 12-hour (`true`) or 24-hour (`false`) clock for time labels. Omit
   * to let `Intl` pick the locale's default hour cycle (default).
   */
  hour12?: boolean;
  /**
   * Adapt the time views to narrow (phone) widths: below 640px a Week/N-days
   * view collapses to a compact 1- or 3-day window (Google-Agenda style),
   * without mutating the store. Defaults to `true`; pass `false` to keep the
   * full view at every width.
   */
  responsive?: boolean;
  className?: string;
}

/** Width below which the time views collapse to a compact day window. */
const COMPACT_BREAKPOINT = 640;
/** Width below which the compact window narrows to a single day. */
const SINGLE_DAY_BREAKPOINT = 480;

export function Calendar(props: CalendarProps): JSX.Element {
  const {
    options,
    store: externalStore,
    hideToolbar,
    responsive = true,
    className,
    locale,
    hour12,
    onEventCreate,
    onEventUpdate,
    onEventClick,
    onSelectSlot,
    onRecurringEdit,
  } = props;

  const { store, snapshot } = useCalendar(externalStore ?? options ?? {});

  // Presentation-only formatters bound to the locale/hour12 props (memoised so
  // views get a stable reference until the settings change).
  const formatters = useMemo(
    () => createFormatters(locale, hour12),
    [locale, hour12],
  );

  const rootRef = useRef<HTMLDivElement>(null);

  // Measure the root width so the time views can collapse on narrow screens.
  // `null` until the first measurement so we never flash the compact layout.
  const [width, setWidth] = useState<number | null>(null);
  useEffect(() => {
    if (!responsive) return;
    const el = rootRef.current;
    if (!el) return;
    const measure = (w: number) =>
      setWidth((prev) => (prev === w ? prev : w));
    measure(el.getBoundingClientRect().width);
    const ro = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (entry) measure(entry.contentRect.width);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [responsive]);

  // Effective view model + compact navigation descriptor. The store/state are
  // never mutated: we recompute the view from an overridden state copy, so the
  // full Week view automatically returns once the screen widens.
  const { effectiveView, compactNav } = useMemo<{
    effectiveView: ViewModel;
    compactNav: CompactNav | null;
  }>(() => {
    const { state, view } = snapshot;
    const collapsible = view.kind === "week" || view.kind === "days";
    if (
      !responsive ||
      width === null ||
      width >= COMPACT_BREAKPOINT ||
      !collapsible
    ) {
      return { effectiveView: view, compactNav: null };
    }
    const nDays = width < SINGLE_DAY_BREAKPOINT ? 1 : 3;
    const compactView = computeView(
      { ...state, view: "days", visibleDays: nDays },
      snapshot.events,
      snapshot.now,
    );
    return { effectiveView: compactView, compactNav: { nDays } };
  }, [responsive, width, snapshot]);

  // Step the cursor by one period, honouring the compact day window when the
  // time view has been collapsed (advance N days instead of a whole week).
  const stepPeriod = useMemo(() => {
    return (dir: 1 | -1): void => {
      if (compactNav) {
        const tz = snapshot.state.timeZone;
        const cursorDate = epochToPlainDate(snapshot.state.cursor, tz);
        const target = addDays(cursorDate, dir * compactNav.nDays);
        // Place at local midday to dodge DST edges, mirroring the core store.
        store.setCursor(startOfDayEpoch(target, tz) + 12 * 3_600_000);
      } else if (dir < 0) {
        store.prev();
      } else {
        store.next();
      }
    };
  }, [store, snapshot, compactNav]);

  const ctx = useMemo(
    () => ({
      store,
      snapshot,
      effectiveView,
      compactNav,
      stepPeriod,
      formatters,
      onEventCreate,
      onEventUpdate,
      onEventClick,
      onSelectSlot,
      onRecurringEdit,
    }),
    [
      store,
      snapshot,
      effectiveView,
      compactNav,
      stepPeriod,
      formatters,
      onEventCreate,
      onEventUpdate,
      onEventClick,
      onSelectSlot,
      onRecurringEdit,
    ],
  );

  // Roll the "now"-dependent state over when the day changes (cheap interval).
  useEffect(() => {
    const id = setInterval(() => store.refresh(), 5 * 60_000);
    return () => clearInterval(id);
  }, [store]);

  // Minimal keyboard navigation: arrows = prev/next period, "t" = today.
  const onKeyDown = (e: React.KeyboardEvent): void => {
    const target = e.target as HTMLElement;
    if (target.tagName === "INPUT" || target.tagName === "SELECT" || target.tagName === "TEXTAREA") {
      return;
    }
    if (e.key === "ArrowLeft") {
      stepPeriod(-1);
    } else if (e.key === "ArrowRight") {
      stepPeriod(1);
    } else if (e.key === "t" || e.key === "T") {
      store.today();
    }
  };

  const view = effectiveView;

  return (
    <CalendarContext.Provider value={ctx}>
      <div
        ref={rootRef}
        className={`calidar${className ? ` ${className}` : ""}`}
        tabIndex={0}
        onKeyDown={onKeyDown}
        role="application"
        aria-label="Calendar"
      >
        {!hideToolbar && <CalendarToolbar />}
        <div className="calidar__view">
          {view.kind === "month" ? (
            <MonthView model={view} />
          ) : view.kind === "agenda" ? (
            <AgendaView model={view} />
          ) : (
            <TimeGridView model={view} />
          )}
        </div>
      </div>
    </CalendarContext.Provider>
  );
}

// packages/svelte/src/Calendar.svelte
<script lang="ts">
  import type {
    CalendarOptions,
    CalendarStore,
    TimeGridViewModel,
  } from "@calidar/core";
  import { computeView, addDays, startOfDayEpoch, epochToPlainDate } from "@calidar/core";
  import { createCalendarState } from "./calendarState.svelte.js";
  import { createFormatters } from "./format.js";
  import type { CalendarCallbacks } from "./types.js";
  import Toolbar from "./Toolbar.svelte";
  import TimeGridView from "./TimeGridView.svelte";
  import MonthView from "./MonthView.svelte";
  import AgendaView from "./AgendaView.svelte";

  interface Props extends CalendarCallbacks {
    /** Provide options to create a store, or an existing store to share one. */
    options?: CalendarOptions;
    store?: CalendarStore;
    /**
     * Adapt the time grid to narrow containers (phone-style). When the root is
     * under 640px wide and the active view is week/days, the calendar renders a
     * compact 1–3 day window instead of squeezing 7 columns. The store is never
     * mutated, so the full Week view returns when the screen widens. Default
     * `true`; set `false` to keep the legacy fixed layout.
     */
    responsive?: boolean;
    /**
     * BCP-47 locale for all labels (weekdays, titles, times). Overrides
     * `navigator.language`. Omit to keep the host's runtime locale (default).
     */
    locale?: string;
    /**
     * Force a 12-hour (`true`) or 24-hour (`false`) clock for time labels. Omit
     * to let `Intl` pick the locale's default hour cycle (default).
     */
    hour12?: boolean;
  }
  const {
    options,
    store: externalStore,
    onEventCreate,
    onEventUpdate,
    onEventClick,
    onSelectSlot,
    responsive = true,
    locale,
    hour12,
  }: Props = $props();

  // Presentation-only formatters bound to the locale/hour12 props, threaded to
  // the toolbar and every view so a forced locale flows through all labels.
  const formatters = $derived(createFormatters(locale, hour12));

  // Resolve the calendar exactly once during init. Reading the store/options
  // here is intentional: like React's useCalendar, we never swap the store
  // after mount — use store actions to mutate state instead.
  // svelte-ignore state_referenced_locally
  const cal = createCalendarState(externalStore ?? options ?? {});

  // Callbacks stay reactive so a host can swap handlers after mount.
  const callbacks = $derived<CalendarCallbacks>({
    onEventCreate,
    onEventUpdate,
    onEventClick,
    onSelectSlot,
  });

  const snapshot = $derived(cal.snapshot);

  let rootEl: HTMLDivElement | undefined = $state();

  // ---- Responsive measurement ---------------------------------------------
  // Measured width of the root container. 0 until the observer fires.
  let rootWidth = $state(0);

  $effect(() => {
    const el = rootEl;
    if (!el || !responsive) return;
    const measure = () => {
      rootWidth = el.clientWidth;
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  });

  // Compact applies only to the time-grid views (week/days) on a narrow screen.
  // month/agenda/day always render as-is.
  const compact = $derived.by(() => {
    if (!responsive) return false;
    if (rootWidth === 0 || rootWidth >= 640) return false;
    const v = snapshot.state.view;
    return v === "week" || v === "days";
  });

  // 1 day under 480px, otherwise 3 — a Google-Agenda-style compact window.
  const compactDays = $derived(rootWidth < 480 ? 1 : 3);

  // Effective time-grid view model. In compact mode we recompute a "days"
  // window from the SAME snapshot without ever mutating the store, so the real
  // Week state is preserved and restored when the screen widens.
  const effectiveTimeGrid = $derived.by<TimeGridViewModel | null>(() => {
    if (!compact) return null;
    const snap = snapshot;
    const vm = computeView(
      { ...snap.state, view: "days", visibleDays: compactDays },
      snap.events,
      snap.now,
    );
    // computeView returns a TimeGridViewModel for the "days" view.
    return vm as TimeGridViewModel;
  });

  // ---- Compact navigation (shift by N days, DST-safe) ---------------------
  function shiftCursorDays(n: number): void {
    const tz = snapshot.state.timeZone;
    const date = epochToPlainDate(snapshot.state.cursor, tz);
    const target = addDays(date, n);
    cal.store.setCursor(startOfDayEpoch(target, tz) + 12 * 3_600_000);
  }

  // Toolbar nav handlers: compact steps by N days, otherwise the store's
  // view-sized prev/next.
  const onPrev = $derived(() =>
    compact ? shiftCursorDays(-compactDays) : cal.store.prev(),
  );
  const onNext = $derived(() =>
    compact ? shiftCursorDays(compactDays) : cal.store.next(),
  );

  // Pass the effective compact days to the Toolbar so the title reflects the
  // range actually on screen (e.g. "23–25 June"). Null outside compact mode.
  const titleDays = $derived(effectiveTimeGrid?.days.map((d) => d.date) ?? null);

  // Minimal keyboard nav: arrows = period, "t" = today. Scoped to when focus is
  // within the calendar root so it never hijacks the rest of the page.
  function onKeydown(e: KeyboardEvent): void {
    const target = e.target as HTMLElement | null;
    if (!rootEl || !target || !rootEl.contains(target)) return;
    if (["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName)) return;
    if (e.key === "ArrowLeft") {
      onPrev();
      e.preventDefault();
    } else if (e.key === "ArrowRight") {
      onNext();
      e.preventDefault();
    } else if (e.key === "t" || e.key === "T") {
      cal.store.today();
      e.preventDefault();
    }
  }
</script>

<svelte:window onkeydown={onKeydown} />

<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  class="cal-root"
  class:cal-root--compact={compact}
  bind:this={rootEl}
  tabindex="0"
  role="application"
  aria-label="Calendar"
>
  <Toolbar store={cal.store} {snapshot} {onPrev} {onNext} {titleDays} {formatters} />

  <div class="cal-body">
    {#if snapshot.view.kind === "month"}
      <MonthView store={cal.store} view={snapshot.view} {callbacks} {formatters} />
    {:else if snapshot.view.kind === "agenda"}
      <AgendaView view={snapshot.view} now={snapshot.now} {callbacks} {formatters} />
    {:else if compact && effectiveTimeGrid}
      <TimeGridView
        store={cal.store}
        view={effectiveTimeGrid}
        now={snapshot.now}
        {callbacks}
        {formatters}
      />
    {:else}
      <TimeGridView
        store={cal.store}
        view={snapshot.view}
        now={snapshot.now}
        {callbacks}
        {formatters}
      />
    {/if}
  </div>
</div>
