// packages/svelte/src/AgendaView.svelte
<script lang="ts">
  import type { AgendaViewModel } from "@calidar/core";
  import type { CalendarCallbacks } from "./types.js";
  import { formatAgendaDay, formatTime } from "./format.js";

  interface Props {
    view: AgendaViewModel;
    now: number;
    callbacks: CalendarCallbacks;
  }
  const { view, now, callbacks }: Props = $props();

  function timeLabel(start: number, end: number, allDay: boolean): string {
    if (allDay) return "All day";
    return `${formatTime(start, view.timeZone)} – ${formatTime(end, view.timeZone)}`;
  }
</script>

<div class="cal-agenda">
  {#if view.sections.length === 0}
    <p class="cal-agenda__empty">No events in this range.</p>
  {/if}
  {#each view.sections as section (section.dayStart)}
    {@const isToday = now >= section.dayStart && now < section.dayStart + 86_400_000}
    <section class="cal-agenda__section">
      <h3 class="cal-agenda__date" class:cal-agenda__date--today={isToday}>
        {formatAgendaDay(section.date)}
      </h3>
      <ul class="cal-agenda__list">
        {#each section.instances as inst (inst.key)}
          <li>
            <button
              type="button"
              class="cal-agenda__item"
              onclick={() => callbacks.onEventClick?.(inst)}
            >
              <span
                class="cal-agenda__dot"
                style={inst.color ? `--cal-event-color:${inst.color}` : ""}
              ></span>
              <span class="cal-agenda__time">
                {timeLabel(inst.start, inst.end, inst.allDay)}
              </span>
              <span class="cal-agenda__title">{inst.title}</span>
            </button>
          </li>
        {/each}
      </ul>
    </section>
  {/each}
</div>

// packages/react/src/AgendaView.tsx
/**
 * Agenda view: a flat, scrollable list grouped into day sections. Good for
 * dense schedules and small screens where a grid would be cramped.
 */
import type { AgendaViewModel, EventInstance } from "@calidar/core";
import { useCalendarContext } from "./context.js";
import { formatAgendaDay, formatTime } from "./format.js";

interface Props {
  model: AgendaViewModel;
}

export function AgendaView({ model }: Props): JSX.Element {
  const { onEventClick } = useCalendarContext();
  const { timeZone } = model;

  if (model.sections.length === 0) {
    return <div className="cal-agenda cal-agenda--empty">No events in this range.</div>;
  }

  return (
    <div className="cal-agenda">
      {model.sections.map((section) => (
        <section key={section.dayStart} className="cal-agenda__section" aria-label={formatAgendaDay(section.date)}>
          <h3 className="cal-agenda__date">{formatAgendaDay(section.date)}</h3>
          <ul className="cal-agenda__list">
            {section.instances.map((inst) => (
              <AgendaRow key={inst.key} instance={inst} timeZone={timeZone} onClick={onEventClick} />
            ))}
          </ul>
        </section>
      ))}
    </div>
  );
}

function AgendaRow({
  instance,
  timeZone,
  onClick,
}: {
  instance: EventInstance;
  timeZone: string;
  onClick?: (instance: EventInstance) => void;
}): JSX.Element {
  return (
    <li>
      <button type="button" className="cal-agenda__row" onClick={() => onClick?.(instance)}>
        <span
          className="cal-agenda__chip"
          style={{ ["--cal-event-color" as string]: instance.color || undefined }}
          aria-hidden="true"
        />
        <span className="cal-agenda__time">
          {instance.allDay
            ? "All day"
            : `${formatTime(instance.start, timeZone)} – ${formatTime(instance.end, timeZone)}`}
        </span>
        <span className="cal-agenda__title">{instance.title}</span>
      </button>
    </li>
  );
}
